# ╭──────────────────────────────────────ImplementationGuide───────────────────────────────────────╮
# │  The properties below are used to create the ImplementationGuide resource. For a list of       │
# │  supported properties, see: https://fshschool.org/sushi/configuration/                         │
# ╰────────────────────────────────────────────────────────────────────────────────────────────────╯
id: fhirtraining.ig
canonical: https://intellisoft-consulting.github.io/FHIR-training-ig-template
name: FHIR TRAINING IG
status: draft
version: 0.1.0
fhirVersion: 4.0.1
# copyright:
copyrightYear: 2021+
releaseLabel: ci-build
title: Intelisoft FHIR TRAINING IG
description: |
  Intelisoft FHIR TRAINING IG
license: CC-BY-SA-4.0
publisher:
  name: Intelisoft
  url: https://github.com/IntelliSOFT-Consulting
  email: mmutesasira@intellisoftkenya.com
  contact: Mozzy Mutesa
experimental: true
parameters:
  excludettl: true
 
# ╭────────────────────────────────────────────menu.xml────────────────────────────────────────────╮
# │  To use a provided ig-data/input/includes/menu.xml file, delete the "menu" property below.     │
# ╰────────────────────────────────────────────────────────────────────────────────────────────────╯
menu:
  Home: index.html
  Table of Contents: toc.html
  Functional Specifications: spec.html
  Technical Specifications:
    Artifacts: artifacts.html
dependencies:
  hl7.fhir.uv.ips: 1.0.0
